### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by oertl** [orlp/polymur-hash#1]
Hi Orson!

If your hash algorithm is already mature, could you add version numbers to the releases? This would allow easier referencing. Past experience has shown that many hash algorithms undergo some (incompatible) improvements over time (see wyhash or komihash). I am very interested in implementing your algorithm in Java and adding it to our [hash4j](https://github.com/dynatrace-oss/hash4j) library.

Otmar

**Comment by orlp** [comment]
I labelled the current version as 1.0: https://github.com/orlp/polymur-hash/blob/master/polymur-hash.h#L2

Should I make backwards-incompatible changes I will increment the major version. I forgot to label the version on git, I will do that now.

**Comment by oertl** [comment]
Thanks a lot!
