### ISSUE TITLE
This is awesome 

### ISSUE THREAD

**Issue by crisdosaygo** [orlp/polymur-hash#4]
I love this. I wanted to create a hash based on some mathematical properties like generators modulo a prime, but couldn't figure out how to make it fast or how to take the right approach. I find your work really inspiring, and it's a useful study guide for how to do this stuff and prove mathematical properties of collisions etc.

I wanted to see a hash that had math properties that actually could be a good hash (passing smhasher3 etc). Umash sounded good, and is very fast, but failed many tests. I love your approach, thanks for publishing it! :)

**Comment by orlp** [comment]
Glad you like it :)
